### ISSUE TITLE
List of Questions

### ISSUE THREAD

**Issue by abieber1408** [abieber1408/Anita-Bieber#1]
## Value proposition

As an <user>user
I want  to<list a question and two possible answers> list a question and two possible answers and the result of the answer.
So that <I can read the question and choose one answer>I can read and choose one correct answer and see the result.
## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

Screen 1
-Answer and question as a differente card.
-The  title "Frage:" and title "Wähle eine Antwort:" is displayed above card.
-The answers should be checkboxes, only one could be checked  with image.
-After clicked on answer should be linked with screen 2.

Screen 2
It should appear the "richtig!!" or the "falsch!!" text on the card.
It should connect to card ...

## Tasks

- [ ] Create database with Questions and answers.
- [ ] Add to App.
- [ ] Create two checkboxes.
- [ ] Link with screen 2.

Screen 2
- [ ] Create Label.
- [ ] Link with card ...

![Image](https://user-images.githubusercontent.com/110246640/227477206-de8eaa62-e5d1-435d-8a1a-81c80e3afa0e.png)

**Comment by liebeckm** [comment]
nice! ☺️ 
my suggestions:
- add the image below the description heading and delete the existing placeholder text
- navbar is not necessary for the moment because the links do not work yet
- task "create card component" is missing
- there is no answer button to click on screen 1
- screen 2 needs a "next question" button maybe?

**Comment by LuYujin9** [comment]
here are my suggestions :

- the Scribble should be under the Description.
- for answers , they should be "input", type is "radius", not "checkbox",
- add a button for answer submit, then people can change their answer before they decide.

**Comment by PReichetanz** [comment]
Hi Anita,

a really good start for your user story! 🎉

I would only like to add one thing in order to simplify your story:

Please consider to show the "richtig" or "falsch" on the same screen as the question for now, because I don't think it's necessary to create a different page for that. If you will need another page for this, you can add it in another user story.
